# Generated by Django 4.0.5 on 2022-06-24 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('twitter', 'twitter'), ('google', 'google'), ('facebook', 'facebook')], max_length=50)),
                ('resource_owner_key', models.CharField(blank=True, max_length=300, null=True)),
                ('resource_owner_secret', models.CharField(blank=True, max_length=300, null=True)),
                ('access_token', models.CharField(blank=True, max_length=300, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
