# Generated by Django 4.0.5 on 2022-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauth',
            name='is_process_complete',
            field=models.BooleanField(default=False),
        ),
    ]
