# Generated by Django 4.0.5 on 2022-06-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useractivation_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='key',
            field=models.CharField(max_length=300),
        ),
    ]
